@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Новые функции - Умный дом

Person(owner, "Собственник", "Владелец недвижимости, пользователь сервисов компании")
System(prop_dev, "PropDevelopment", "Информационная система компании PropDevelopment")

System_Ext(smart_home, "Партнерская система «Умный дом» партнёра", "Управляет домофоном и шлагбаумом, распознает лица и номера машин")
System_Ext(smart_intercom, "Интеллектуальный домофон", "Открывает дверь, распознает лица собственников квартир")
System_Ext(smart_barrier, "Интеллектуальный шлагбаум", "Открывает шлагбаум, распознает номера машин собственников квартир")

Rel(owner, prop_dev, "Управляет домофоном", "Мобильное приложение")
Rel(owner, prop_dev, "Управляет шлагбаумом", "Мобильное приложение")
Rel(owner, prop_dev, "Загружает номера автомобилей", "Мобильное приложение")
Rel(owner, prop_dev, "Загружает биометрию", "Мобильное приложение")

Rel(prop_dev, smart_home, "Управляет домофонами, шлагбаумами по запросу собственников")
Rel(smart_home, prop_dev, "Авторизация номеров машин владельцев для открытия шлагбаумов")
Rel(smart_home, prop_dev, "Авторизация биометрии владельцев для открытия домофонов")

Rel(smart_home, smart_intercom, "Управляет домофонами")
Rel(smart_home, smart_barrier, "Управляет шлагбаумами")

Rel(smart_intercom, smart_home, "Направляет биометрию на авторизацию для открытия дверей")
Rel(smart_barrier, smart_home, "Направляет фото автомобилей на авторизацию для открытия шлагбаумов")


@enduml