apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuzya-devops
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srv-updater-user
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vasya-developer
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kolya-ib
  namespace: prop-development